### ISSUE TITLE
Slack channel inaccessible. 

### ISSUE THREAD

**Issue by prpr2770** [riswords/quiche#1]
The slack channel you've indicated is inaccessible. Also, is it possible to obtain some documentation of the code or any resources to understand the structure of the code. Additionally, the PLDI'22 [website](https://pldi22.sigplan.org/details/egraphs-2022-papers/1/Quiche-A-Python-Implementation-of-E-Graphs) which describes your work doesn't have any linked resources. Would it be possible to view the presentation slides/paper? 
Thank you.

**Comment by riswords** [comment]
Hello, thanks so much for your interest! I apologize for my slowness in responding, not sure what happened with the notifications. I just updated the Slack link- if you're still looking to join and get more info. I can't get it right this minute, but I will put up presentation slides on this repo ASAP.

**Comment by riswords** [comment]
PDF and PPTX versions of the slides are up. The PowerPoint version includes the slide notes, such as they are. Additionally, I updated the README with a link to the YT recording of the EGRAPHS workshop (link goes directly to my talk, but the recording includes the full EGRAPHS workshop if there are other talks you're interested in).
